config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  
    resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
   end

    resources :rooms, only: [:create, :index, :show] do
    resources :messages, only: [:create]
    end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 35}
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord

    attachment :image
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :read_counts, dependent: :destroy

    validates :location, presence: true, length: { maximum: 15}
    validates :text, presence: true, length: { maximum: 195 }
    validates :image, presence: true

    enum status: { published: 0, draft: 1 }

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
    belongs_to :user
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :entries, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :read_counts, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy


  attachment :profile_image
 
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def show
    @book_detail = Book.find(params[:id])
    unless ReadCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      current_user.read_counts.create(book_id: @book_detail.id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order
    @posts = @posts.where('location LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def show
    @post = Post.find(params[:id])
    
    unless ReadCount.where(user_id: current_user.id, post_id: @post.id).exists?
    ReadCount.create(user_id: current_user.id, post_id: @post.id)
    end
    
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :location, :text, :image, :status)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!

  def create
    @room = Room.create
    @current_entry = @room.entries.create(user_id: current_user.id)
    @another_entry = @room.entries.create(user_id: params[:entry][:user_id])
    redirect_to room_path(@room)
  end

  def index
    my_room_id = current_user.entries.pluck(:room_id)
    @another_entries = Entry
                       .where(room_id: my_room_id)
                       .where.not(user_id: current_user.id)
                       .preload(room: :messages).preload(user: { icon_attachment: :blob })
  end

  def show
    @room = Room.find(params[:id])
    if @room.entries.where(user_id: current_user.id).present?
      @messages = @room.messages.all
      @message = Message.new
      @entries = @room.entries
      @another_entry = @entries.where.not(user_id: current_user.id).first
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_index.html.erb
 <div class="row mt-3 mb-3 align-self-end">
      <%= form_with url: posts_path, method: :get, local: true do |f| %>
        <%= f.text_field :search %>
        <%= f.submit '検索する', name: nil %>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <%  posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
            <p class="caption"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
       <% end %>
    </div>
    <%= paginate posts %>

app/views/posts/confirm.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
    </div>
    <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mb-3">
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="row">
      <%= form_with model: @post, local:true do |f| %>
    
        <div class="form-group mb-3">
          <label class="form-label">旅行先</label>
          <%= f.text_field :location, class:"form-control" %>
        </div>
        
        <div class="form-group mb-3">
          <label class="form-label">感想</label>
          <%=f.text_area :text, rows:10, class:"form-control" %>
        </div>

        <div class="form-group mb-4">
          <label class="form-label">画像</label><br>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]},{},{class: "custom-select w-25 mb-3"} %>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %><br>
        <%= link_to '投稿詳細ページへ' , post_path(@post), class: "btn btn-dark mt-3" %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>
    <div class="row mt-3 mb-3 align-self-end">
      <%= form_with method: :get, local: true do |f| %>
        <%= f.text_field :search %>
        <%= f.submit '検索する', name: nil %>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
            <p class="caption"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
       <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>




 

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行新規投稿</h1>
    </div>
    <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3">
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="row mt-5">
      <%=  form_with model: @post, local:true do |f| %>
        <div class="form-group mb-3">
          <label class="form-label">【旅行先】</label>
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【感想】</label>
          <%= f.text_area :text, rows:10, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【画像】</label><br>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]},{},{class:"custom-select w-25 mb-3"} %>
        </div>
        <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5 mb-5">
      <h1 class="font-weight-normal">旅行投稿詳細</h1>
    </div>
    <% if @comment.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3">
        <%= @comment.errors.count %>件のエラーが発生しました
        <% @comment.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="container d-flex mt-5">
      <div class="d-block">
        <p class="caption"><%= @post.user.name %></p>
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "450x350" %><br>
        <p class="caption"><%= @post.location %>
          <% if @post.favorited_by?(current_user) %>
            <%= link_to post_favorites_path(@post), data: { turbo_method: :delete }, class: "favorite_btn" do %>
              ♥<%= @post.favorites.count %>いいね
            <% end %>
          <% else %>
            <%= link_to post_favorites_path(@post), data: { turbo_method: :post }, class: "favorite_btn" do  %>
              ♡<%= @post.favorites.count %> いいね
            <% end %>
          <% end %> 
          
          <span class="ml-3">
        <i class="fa-solid fa-eye"></i> 閲覧数：<%= @post.read_counts.count %>
      </span>
      </p>

        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>
      <% if @post.user == current_user %>
        <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
        <%= link_to '削除する', post_path(@post.id), data: { turbo_method: :delete, turbo_confirm: "本当に消しますか？"} , class: "btn btn-danger" %><br>
      <% end %>
        <%= link_to '投稿一覧ページへ',posts_path , class: "btn btn-dark mt-3" %>
      </div>
      <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local:true) do |f| %>
          <%= f.text_area :comment, :size =>"60x3",placeholder: "コメントする" %>
          <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        <% end %>

        <p>コメント件数: <%= @comments.count %></p>
        <% @comments.each do |comment| %>
            <div class="comments-index mb-2">
              <%= comment.user.name %>
              <%= comment.created_at.strftime('%Y/%m/%d') %><br>
              <div class="d-flex">
                <%= comment.comment %>
                <% if comment.user == current_user %>
                  <div class="comment-delete">
                   <%= link_to "削除", post_comment_path(comment.post,comment), data:{turbo_method: :delete}, class: "btn-sm btn-danger" %>
                  </div>
                <% end %>
              </div>
            </div>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>






app/views/rooms/index.html.erb
<% @another_entries.each do |entry| %>
  <%= link_to room_path(entry.room), style: "text-decoration: none;" do %>
    <div class="card">
      <div class="card-body">
        <div class="d-flex">
          <div class="chat-avatar">
            <%= link_to user_path(entry.user) do %>
              <%= image_tag entry.user.icon, class: "message_icon_img me-3" %>
            <% end %>
          </div>
          <div class="chat-user-name">
            <span class="fw-bold me-2"><%= entry.user.name %></span>
            <span class="username">@<%= entry.user.username %></span>
            <div class="chat-text">
              <%= entry.room.messages.last&.message %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<div class="chat-room-wrapper vh-100 d-flex flex-column">
  
  <% if @message.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="chat-header d-flex align-items-center py-3 px-4 position-relative">
    <%= link_to root_path, class: "text-dark position-absolute start-0 ms-4" do %>
      <i class="fa-solid fa-arrow-left arrow-left"></i>
    <% end %>

    <h3 class="m-0 fs-3 fw-bold mx-auto">
    <%# ➁ 名前を青色、残りを黒色に色分け %>
    <span class="text-primary"><%= @another_entry.user.name %> さん</span><span class="text-dark">とのトークルーム</span>
    </h3>
  </div>

  <%# メッセージ表示エリア %>
  <div class="chat-body p-4 flex-grow-1 overflow-auto">
    <div class="chat-content-box shadow-sm p-4 mx-auto">   
      
      <% @messages.each do |m| %>
        <% if m.user_id == current_user.id %>
          <%# 自分の投稿 %>
          <div class="d-flex justify-content-end mb-4">
            <div class="my-message-box ">
              <%= m.message %>
            </div>
          </div>
        <% else %>
          <%# 相手の投稿（左側・白系） %>
          <div class="d-flex justify-content-start mb-4 align-items-start">
            <div class="other-message-box">
              <%= m.message %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# 入力フォームエリア %>
  <div class="chat-form-box p-4 w-100 d-flex justify-content-center bg-transparent">
    <%= form_with model: [@room, @message], local: true,class: "w-100" do |f| %>
      <%# gap-2 を追加して、入力欄とボタンの間に隙間を作ります %>
      <div class="chat-form-group d-flex gap-2 mx-auto" style="max-width: 700px;">
        
        <%= f.text_field :message, class: "form-control border-0 bg-white shadow-sm ", placeholder: "メッセージを入力して下さい" %>
        <%= f.submit "送信する", class: "btn btn-primary shadow-sm" %>
      </div>
    <% end %>
  </div>
</div>